### ISSUE TITLE
Events are not supported

### ISSUE THREAD

**Issue by SuperJMN** [SuperJMN/OmniXAML#10]
Events like `<Button Click="SomeHandler" />` are not supported.

**Comment by cloudRoutine** [comment]
Or perhaps events like `< Button Click =' {Event Path=ClickEvent, EventStream Path= MyClickStream }' />`?  A hook to trigger and a hook to subscribe.
Either way, events are essential!

**Comment by ReedCopsey** [comment]
I'd actually prefer this to work directly against the DataContext - it'd lead people towards better designs.  Something like `<Button Click='{EventBinding SomeHandler}' />` where SomeHandler was defined in the DataContext.

Ideally, you'd have the option of doing a conversion for the EventArgs -> T, so you could have SomeHandler be defined as a delegate property, ie:

`<Canvas OnMouseMove='{EventBinding Move, Converter=MouseEventArgsToPointConverter}' />`

with 
```
private void _move(Point location)
{
   // ... 
}
public Action<Point> Move { get { return this._move; } }
```

**Comment by SuperJMN** [comment]
I like that syntax a lot. Of course, this is a very important feature. I need to take a look at how to implement it.

**Comment by SuperJMN** [comment]
+1 to the DataContext, @ReedCopsey

**Comment by ReedCopsey** [comment]
The nice things are:

1) The handler works in the VM, not the View layer, leading to better designs *by default*
2) No requirement for compile-time support - can all wire at runtime
3) Decouples from View types in the handler via a converter (optional), so your VM/Model layers can stay "pure"

**Comment by ReedCopsey** [comment]
Another option for event handling: Create your own `Observable<T>` class, and use it as a binding target:

```
class VM
{
   // ...
   // Having property:
   public Observable<Point> Move { get; } = new Observable<Point>();
}
```

Then the xaml could be `<Canvas OnMouseMove='{Observe Move, Converter=MouseEventArgsToPointConverter}' />`

If Observer<T> implemented IObservable<T>, it'd allow you to very easily compose reactive streams, even from languages like C#.

**Comment by cloudRoutine** [comment]
^ Now that sounds great

**Comment by jkoritzinsky** [comment]
Any progress on implementing this?

**Comment by grokys** [comment]
I think the ideas mentioned by @ReedCopsey are a really good idea, but I think for us they'll be Perspex markup extensions, as OmniXAML doesn't know anything about binding and `DataContext`s etc.

For OmniXAML it would be good to just have basic event support.

**Comment by jkoritzinsky** [comment]
Super basic event support is in #106. It has built in handling for non-attached events and provides enough information and tooling to users to implement support for attached events. I'll continue to work on implementing attached events support and trying to minimize the new API surface.

**Comment by SuperJMN** [comment]
Merged in the "events" branch. Thanks, Jeremy!

**Comment by zezba9000** [comment]
Was this merged into master?

**Comment by SuperJMN** [comment]
@zezba9000 Not yet. It's in the v2 branch, but I'll turn this branch into master soon. The problem is that I don't know how to proceed with the switch. I've never done something similar with Git.

**Comment by jkoritzinsky** [comment]
@SuperJMN there are two ways.

1. Change the default branch to omnixaml-v2
2. Push master to a new branch and then force push omnixaml-v2 to master.

I'd suggest doing the first option.

**Comment by SuperJMN** [comment]
I've successfully made the change. Thanks for the suggestions! I discarded merging both branches because, they are essentially 2 different projects. V2 started from scratch and, although it reuses some code from v1, it's a minimal part of the whole, so a merge could be confusing and far more problematic.
