### ISSUE TITLE
TopDownValueContext.StoredInstances incorrect?

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#105]
Not sure about this, but I believe that `TopDownValueContext.StoredInstances` is incorrect. Consider the following XAML:

```
<Styles xmlns='https://github.com/perspex'
        xmlns:mut='https://github.com/perspex/mutable'
        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'>
    <Style>
        <Style.Resources>
            <Color x:Key='color'>#ff506070</Color>
            <mut:SolidColorBrush x:Key='brush' Color='{StyleResource color}'/>
        </Style.Resources>
    </Style>
</Styles>
```

At the point of evaluating the `{StyleResource}` the `StoredInstances` collection contains the following:
1. `Styles`
2. `Style`
3. `Dictionary<string, object>` (i.e. `Style.Resources`)
4. `Color`
5. `SolidColorBrush`
6. `StyleResourceExtension`
7. `StyleResourceBinding`

I believe that item 4 is incorrect - `Color` is a _sibling_ of `SolidColorBrush` and so shouldn't appear in the `StoredInstances`.

**Comment by SuperJMN** [comment]
Hey, I think it's correct: If 4. (Color) wasn't available just before SolidColorBrush, then, the StaticResource extension would be able to find it. StoreInstances doesn't behave like a stack, but like an additive list). I may be wrong, but I think it's the way it should work :)

**Comment by grokys** [comment]
Hmm, that doesn't sound right to me - the `StyleResource` extension isn't looking up the `color` in the XAML - it's looking it up in the underlying object model.

At least all of my use-cases require a stack leading up to the current element - including siblings in there will likely result in the *wrong* element being found, unless you introduce a way to specify the relationship to the current element.

**Comment by SuperJMN** [comment]
TopDownValueContext is no longer used. OmniXAML v2 will handle the parsing process in a completely different way. I'll reopen if this applies in the future :) Thanks for reporting!!
