### ISSUE TITLE
Unable to pull in Xaml Namespaces for Prism (Probably other libraries too)

### ISSUE THREAD

**Issue by danwalmsley** [SuperJMN/OmniXAML#108]
I created an issue in persex too incase its a Perspex problem.

https://github.com/Perspex/Perspex/issues/523

Add prism as a nugget package to project.

Then try and add xmlns for prism,... omnixaml cant resolve it,

**Comment by grokys** [comment]
I think this is more a Perspex issue than OmniXAML. Could you close this? We'll track it in the Perspex repos.

**Comment by danwalmsley** [comment]
ok
