### ISSUE TITLE
Extra white spaces in Binding Path will cause LoadException

### ISSUE THREAD

**Issue by flyingxu** [SuperJMN/OmniXAML#110]
`Text="{Binding Path = StringValue}"` is a valid XAML in WPF, but in OmniXAML, it will cause LoadException. (Please notice the 2 extra white spaces before and after `=`.
If the 2 white spaces are removed `Text="{Binding Path=StringValue}"`, it's valid in OmniXAML.

**Comment by SuperJMN** [comment]
Nice to know! I'll catch that! Thanks for reporting :D

**Comment by grokys** [comment]
Related #111.

**Comment by SuperJMN** [comment]
Fixed yesterday! please, check.
