### ISSUE TITLE
Markup Extension Parsing

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#111]
OmniXAML's markup extension parser only allows certain non-alphanumeric chars, and does not conform to the spec:

https://msdn.microsoft.com/en-us/library/ee200269.aspx

**Comment by jogibear9988** [comment]
Maybe this would help you here: https://github.com/icsharpcode/WpfDesigner/blob/master/WpfDesign.XamlDom/Project/MarkupExtensionParser.cs

**Comment by SuperJMN** [comment]
Could you give some non-working example? Just to clarify. Thank you!

**Comment by grokys** [comment]
`{Binding Foo^.Bar}`

**Comment by SuperJMN** [comment]
It still don't conform to the standard, but I think the changes I commited to master yesterdady are enough for now :)
