### ISSUE TITLE
[Q] How to load custom objects?

### ISSUE THREAD

**Issue by 0xFireball** [SuperJMN/OmniXAML#117]
I'm defining some simple view-like objects and want to be able to load instances from Xaml. They are completely unrelated to WPF; I just want to be able to use OmniXaml to load Xaml and create an instance of my class.

Next, I would also like to be able to define a DataContext-like property and allow binding to a viewmodel-like object.

Unfortunately, as there is no documentation, I'm posting here.

Thanks for the help!

**Comment by SuperJMN** [comment]
Hi Fireball! I can help you with it. First of all, you should define a mapping between your classes and the XAML types you will want to inflate. You can do it using the `XmlnsDefinitionAttribute` inside your AssemblyInfo.cs, like this:
`[assembly: XmlnsDefinition("my_xml_namespace", "MyClrNamespace")]`

Then, in your root object of your XAML you should add this "xmlns"

`<MyRootObj xmlns="my_xml_namespace">`

After that, OmniXAML will be able to instantiate the classes inside your namespace. 

Now, in your starting point of your code, like in Program.cs or App.xaml.cs, depending on your kind of application, put this:

            var runtimeTypeSource = RuntimeTypeSource.FromAttributes(Assemblies.AssembliesInAppFolder);
            var loader = new DefaultLoader(runtimeTypeSource);
var dict = new Dictionary<string, object>();
            var myObj= loader.FromPath("MyFile.xaml", new Settings { InstanceLifeCycleListener = new DefaultInstanceLifeCycleListener(), ParsingContext = dict });

And your objects will load just right!

You can check it and if you have any problem, you can send me your code to http://scr.im/superjmn
