### ISSUE TITLE
Support for x:Class

### ISSUE THREAD

**Issue by SuperJMN** [SuperJMN/OmniXAML#12]
It's unsupported.

**Comment by ewinnington** [comment]
What would be needed for x:Class support? 

With https://github.com/dmetzgar/corewf looking for an XAML implementation that supports x:Class, as described here https://github.com/dotnet/corefx/issues/2394#issuecomment-244534065 , it would be great to know if that can bring some help / interest to OmniXAML.

**Comment by SuperJMN** [comment]
Working in v2
