### ISSUE TITLE
Should follow XAML whitespace processing rules

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#17]
In WPF, the following:

    <TextBox>
        Hello
        World
    </TextBox>

Produces a TextBox with a single line reading "Hello World". In OmniXaml, the newlines are copied verbatim from the XAML into the text, resulting in a TextBox with 4 lines.

OmniXaml should follow XAML whitespace processing rules:

https://msdn.microsoft.com/en-us/library/ms788746(v=vs.110).aspx

**Comment by SuperJMN** [comment]
Gonna fix it ASAP.

**Comment by SuperJMN** [comment]
Closed until a new whitespace problem pops up!
