### ISSUE TITLE
Any way to use System.TypeConverter instead of OmniXaml.TypeConversion.ITypeConverter?

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#21]
Is there any way to use `System.TypeConverer` instead of `OmniXaml.TypeConversion.ITypeConverter`? Using the System type would mean that Perspex could have a shared set of type converters that can be used by any type of markup.

**Comment by SuperJMN** [comment]
I'm sorry, I tried hard to use it, but it's an integral part of the full .NET Framework and it's not available for Portable Class Libraries. What I could do is set everything in another package, for example a part of the Glass library, that could be used in other projects that have no relationship with OmniXAML.

**Comment by grokys** [comment]
Oh OK. It seemed to be available in the pcls when I tried, though not at my computer to check right now.

**Comment by SuperJMN** [comment]
It's under the assembly System.ComponentModel :(
