### ISSUE TITLE
Support for saving xaml files?

### ISSUE THREAD

**Issue by amerkoleci** [SuperJMN/OmniXAML#22]
Is possible to save object as XAML, loading is ok but maybe would be better to support saving too.

**Comment by SuperJMN** [comment]
Writing XAML, in my opinion, is almost useless for any normal application scenarios. The XAML that a writer would produce would only have final values of everything. No markup extensions, no ResourceDictionaries, no templates...

It would be reduced to a static representation of the original XAML.

I don't see any real utility. Maybe for displaying a snapshot?

**Comment by SuperJMN** [comment]
Closed for now
