### ISSUE TITLE
XamlTypeRespository.GetByQualifiedName and default namespace.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#23]
In a type converter if I have a string such as `"foo:Button"` I can pass it to `XamlTypeRespository.GetByQualifiedName` and it will resolve it for me.

However, if `Button` is in the default namespace, and I pass simply `"Button"` to `XamlTypeRespository.GetByQualifiedName` then it fails with

     The prefix Button is not registered

Obviously, "Button" is not a prefix, it's a type in the default namespace. Shouldn't this be handled?

**Comment by SuperJMN** [comment]
Fixed with commit https://github.com/SuperJMN/OmniXAML/commit/c6dda85350af3dc0cac5b715242fecfe4c606cb7
