### ISSUE TITLE
OmniXAML ignores namespace

### ISSUE THREAD

**Issue by kekekeks** [SuperJMN/OmniXAML#26]
https://github.com/Perspex/Perspex/blob/8564a74fc1b4eb6d5877167ee25b21c1d791c2cd/src/Markup/Perspex.Markup.Xaml/Context/PerspexWiringContext.cs - here we register only 3 namespaces, but OmniXAML somehow finds `Perspex.Styling.Style`.

**Comment by kekekeks** [comment]
XamlTestApplication: MainWindow.xaml
```xml
<Window x:Class="XamlTestApplication.MainWindow"
        xmlns="https://github.com/perspex"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" 
        Title="Perspex Test Application" Height="350" Width="525">
    <Window.Styles>
        <Style>
            
        </Style>
    </Window.Styles>
</Window>
```

**Comment by SuperJMN** [comment]
I cannot reproduce it with that XAML and the commit you specified (8564a74fc1)
