### ISSUE TITLE
TopDownValueContext not returning parent element

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#28]
In a converter, I should be able to use TopDownValueContext.GetLastInstance to get the parent object but it's not working. See here the `style-xaml` branch in Perspex at this line (uncomment it! ;) )

https://github.com/Perspex/Perspex/blob/style-xaml/src/Markup/Perspex.Markup.Xaml/Converters/PerspexPropertyConverter.cs#L42

**Comment by SuperJMN** [comment]
I will take care of this :)

**Comment by SuperJMN** [comment]
Fixed with https://github.com/SuperJMN/OmniXAML/commit/586e2e521c85a4b111c394e8aee178bbdfc9c1df
