### ISSUE TITLE
DependsOn in Perspex

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#30]
I'm trying to add a property dependency in Perspex from `SelectingItemsControl.SelectedIndex` to `ItemsControl.Items`, however we can't use the OmniXaml `DependsOnAttribute` as we don't want `Perspex.Controls` to have a dependency on OmniXaml.

What is the best way to allow OmniXaml use our own `DependsOnAttribute`?

**Comment by SuperJMN** [comment]
Nice question! attribute-less configuration coming soon :) Anyways, there is still a way to do it overriding this method:

https://github.com/SuperJMN/OmniXAML/blob/f3f909beaca21b0a10c066f9fcb079fcff4a7647/Source/OmniXaml/Typing/MutableXamlMember.cs#L30

**Comment by SuperJMN** [comment]
Done! https://github.com/SuperJMN/OmniXAML/commit/7b13ebcde030df9f8d538917e57b3a34ea9edf32

**Comment by grokys** [comment]
Could you repoen this due to fix not working ;)
