### ISSUE TITLE
Consider Exposing a Pipeline

### ISSUE THREAD

**Issue by Michael-DST** [SuperJMN/OmniXAML#32]
One thing I have been thinking about in a Xaml Serializer is this notion of a pipeline.  It would be really awesome to be able to feature a Xaml serializer that is extensible and allows you to get notified when:

- An object is about to be created
- An object has been created
- An object's property is about to be set
- An object's property has been set.
- ... others?

This is something that System.Xaml is missing, but should be considered here. :)  Again, I would be interested in assisting with this!

**Comment by SuperJMN** [comment]
It's feasible and not difficult, but can you please expose an example of why do you want it? ;)

**Comment by Michael-DST** [comment]
Gladly.  Let's say I have a component that assigns default values to objects based on metadata that is defined on their properties.  Usually what happens is I new up the object and call this component's Apply method.  Since the Xaml parser is creating the objects in Xaml, how do I access the objects it creates to apply the properties?  I have to use funky references of some sort (if I am lucky).  Not pretty.  Having hooks into the object creation pipeline would allow easy access to perform this action on every object it creates.

Not to mention things like instrumentation and logging?  Or whatever people might use when this see this capability.

It's all about possibilities. :)

**Comment by SuperJMN** [comment]
You'll be happy to know that every object OmniXAML instatiates is created using an ITypeFactory that is under your control :) The only thing that isn't handled easily is the assignment of values to each property. Do you need to intercept that? If so, then I will try to implement it.

**Comment by Michael-DST** [comment]
Awesome @SuperJMN.  Gooooood thinking.  I don't particularly need to intercept property values, but I think it would add value knowing it is there.  Anything to make this THE superior Cross-Platform Xaml System is a win, IMO. :)

**Comment by SuperJMN** [comment]
Big thanks, Michael! I think it's becoming more robust each day. 

By the way, I'm closing this issue for the moment. If you feel the feature I told you isn't enough, feel free to tell me :)
