### ISSUE TITLE
Potential NullReferenceException in LookupDependencies

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#33]
In the code you linked me in my previous issue, I can see a potentional NRE:

https://github.com/SuperJMN/OmniXAML/blob/f3f909beaca21b0a10c066f9fcb079fcff4a7647/Source/OmniXaml/Typing/MutableXamlMember.cs#L33

```
var dependsOnAttributes = underlyingType.GetRuntimeProperty(Name)?.GetCustomAttributes<DependsOnAttribute>();
return dependsOnAttributes.Select(attr => DeclaringType.GetMember(attr.PropertyName));
```

If `underlyingType.GetRuntimeProperty(Name)` returns null, `dependsOnAttributes.Select()` will cause an NRE.

**Comment by SuperJMN** [comment]
Thanks! I will fix it!

**Comment by SuperJMN** [comment]
It's now fixed with the latest version :)
