### ISSUE TITLE
OmniXAML is GPL

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#35]
OmniXAML is currently GPL, which makes it incompatible with Perspex and I imagine means that it won't see much use elsewhere either.

People on the reddit thread have been pointing this out, I didn't realise: https://www.reddit.com/r/csharp/comments/3lwzvb/perspex_alpha_2_perspex_is_a_cross_platform_net/

It's a real problem that means people can't really use Perspex for much right now. Would you consider moving to a more permissive licence such as MIT?

**Comment by SuperJMN** [comment]
OmniXAML is now MIT :)

**Comment by grokys** [comment]
:party:

**Comment by Kryptos-FR** [comment]
Hello.

I'd like to use OmniXaml in my project but I'm unsure about the copyright and license restrictions. What is the current license of OmniXaml? The LICENSE file that existed 2 years ago is gone in master and the Nuget page doesn't display a license either.

Thanks.
