### ISSUE TITLE
Perspex's Control.Name must be set before adding to tree.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#40]
Perspex requires the `Control.Name` to be set before the control is added to the visual tree. Currently, OmniXAML tries to set it after it's added to the tree, causing an Exception.

Is this possible in OmniXAML?

**Comment by SuperJMN** [comment]
It's possible, of course. I'll have to check the code to intercept the exact point where to set the name.

**Comment by SuperJMN** [comment]
Fixed with https://github.com/SuperJMN/OmniXAML/commit/87a7cf0cb2f54420a7678b746d1eefbefa1e7e3e
Please, verify that it works in Perspex! :)

**Comment by grokys** [comment]
On the Perspex `xaml-control-themes` branch the following XAML in `App.paml`:

	<Application x:Class="XamlTestApplicationPcl.XamlTestApp"
			xmlns="https://github.com/perspex"
			xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
	  <Application.Styles>
		<Style Selector="Button">
		  <Setter Property="Background" Value="#ffaaaaaa"/>
		  <Setter Property="BorderBrush" Value="#ffaaaaaa"/>
		  <Setter Property="BorderThickness" Value="2"/>
		  <Setter Property="Foreground" Value="Black"/>
		  <Setter Property="HorizontalContentAlignment" Value="Center"/>
		  <Setter Property="VerticalContentAlignment" Value="Center"/>
		  <Setter Property="Template">
			<ControlTemplate TargetType="Button">
			  <Border Name="border"
					  Padding="3"
					  Background="{TemplateBinding Background}"
					  BorderBrush="{TemplateBinding BorderBrush}"
					  BorderThickness="{TemplateBinding BorderThickness}">
				<ContentPresenter Name="presenter"
								  Content="{TemplateBinding Content}"
								  TextBlock.Foreground="{TemplateBinding Foreground}"
								  HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
								  VerticalAlignment="{TemplateBinding VerticalContentAlignment}"/>
			  </Border>
			</ControlTemplate>
		  </Setter>
		</Style>
		<Style Selector="Button:pointerover /template/ Border#border">
		  <Setter Property="BorderBrush" Value="#ff888888"/>
		</Style>
		<Style Selector="Button:pressed  /template/ Border#border">
		  <Setter Property="Background" Value="#ff888888"/>
		</Style>
		<Style Selector="Button:disabled /template/ ContentPresenter#presenter">
		  <Setter Property="Opacity" Value="0.5"/>
		</Style>
	  </Application.Styles>
	</Application>

Causes the exception:

    Cannot set Name : control already added to tree.

With the `presenter` control.

**Comment by grokys** [comment]
I think this is now fixed.
