### ISSUE TITLE
Unable to Parse {Binding Property, Mode=TwoWay}

### ISSUE THREAD

**Issue by danwalmsley** [SuperJMN/OmniXAML#45]
I have to change to Binding Path=x, Mode=y to get it to work.

**Comment by SuperJMN** [comment]
Another example: <ListBox Items="{Binding Items}" SelectedItem="{Binding Selected, Mode=TwoWay}"/>

**Comment by grokys** [comment]
This seems dependent somehow on the nesting in XAML - if the binding is in a top-level control or a child of a top-level control `{Binding Selected, Mode=TwoWay}` seems to work, however if it is any further down in the tree than that, OmniXAML doesn't seem to parse it.

**Comment by SuperJMN** [comment]
OK, men. I have something to entertain myself during the weekend :) Let's see what is this issue about!

**Comment by SuperJMN** [comment]
Do you have some failing test or branch? It would speed up my testing. Thanks!

**Comment by grokys** [comment]
Yep, in Perspex/samples/BindingTest/MainWindow.paml remove `Path=` from the line:

    <TextBox Watermark="One Way" UseFloatingWatermark="True" Text="{Binding Path=StringValue, Mode=OneWay}"/>

And you will see the error when run.

**Comment by SuperJMN** [comment]
Thank you! I will hunt for it.

**Comment by SuperJMN** [comment]
Solved with commit https://github.com/SuperJMN/OmniXAML/commit/536f4f7ccc2bd9583bc6903e8ae60885597dbae5 oh yeah!

**Comment by grokys** [comment]
Whoop!
