### ISSUE TITLE
Styles is not recognised as a collection.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#48]
The following xaml produces an error:

    <Application.Styles>
      <Styles>
        <Style Selector="Button"/>
      </Styles>
    <Application.Styles>

```
Exception thrown: 'OmniXaml.XamlParseException' in Perspex.Markup.Xaml.dll

Additional information: Cannot get the content property for the type Perspex XAML Type XamlType: Styles
```

However `Styles` is defined as 

    public class Styles : PerspexList<IStyle>, IStyle

Which means it's a collection that should accept `<Style>` objects without a `Content` property.

**Comment by SuperJMN** [comment]
Fixed!!
