### ISSUE TITLE
Does IContentPropertyProvider need to implement IAdd<ContentPropertyDefinition>, IEnumerable<ContentPropertyDefinition>?

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#49]
I've just implemented my own `IContentPropertyProvider` and notice that I need to implement `IAdd` and `IEnumerable` on it, however these methods doesn't actually seem to be used.

Are those interfaces needed on `IContentPropertyProvider`?

**Comment by SuperJMN** [comment]
I have to check it, but if I remember correctly, the IAdd interface is used for a method named "AddAll" that is used for attribute-based Content Property autoregistration.

**Comment by SuperJMN** [comment]
Yes, it's for convenience, so the answer its yes, it should. Any problem with it? I plan to separate Glass into an independent library so common interfaces could be segregated to avoid *toxic* dependencies.
