### ISSUE TITLE
Trying to set property twice ignores second attempt.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#51]
In light of #50 I tried to work around the problem by using the long-form binding syntax:

```
            <TextBlock Name="watermark"
                       Opacity="0.5"
                       Text="{TemplateBinding Watermark}"
                       IsVisible="{TemplateBinding IsWatermarkVisible}">
              <TextBlock.IsVisible>
                <Binding RelativeSource="{RelativeSource TemplatedParent}"
                         SourcePropertyPath="Text"
                         Converter="{Static local:StringNullOrEmpty.Instance}"/>
              </TextBlock.IsVisible>
            </TextBlock>
```

However, I didn't notice that I was trying to set `IsVisible` twice, and was finding that the second time was ignored. Should throw an exception.

**Comment by SuperJMN** [comment]
Aha, nice! So it works, but it should throw when the user sets the property twice, isn't it?

**Comment by grokys** [comment]
Yes, at first I thought that doing a long-form `<Binding>` wasn't working, but then I noticed that I was setting the property twice.

**Comment by SuperJMN** [comment]
The check for duplicated attributes is costly :S I can implement the check to be performed by default, with the ability to disable it by configuration. What do you think?

**Comment by SuperJMN** [comment]
Fixed in v2 (for attributes)
