### ISSUE TITLE
Collection top-level element does not work.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#52]
Having a top-level element that is a collection does not seem to work. Something like this:

    <Collection>
        <Item>Foo</Item>
        <Item>Bar</Item>
    </Collection>

Does not seem to work. This is what happens when I try to do it in Perspex:

```
Exception thrown: 'OmniXaml.XamlParseException' in Perspex.Markup.Xaml.dll

Additional information: Cannot find a property named "_UnknownContent" in the type Perspex.Themes.Default.DefaultTheme
```

**Comment by grokys** [comment]
I will try to at least submit a unit test for this, and maybe, hopefully, perhaps, fix it ;)

**Comment by grokys** [comment]
This seems to only be a problem when a root instance is provided.

**Comment by SuperJMN** [comment]
Nice! I'll double check why this was happening and will review your commit! Thanks in advance :D
