### ISSUE TITLE
Support attached NameScopes

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#57]
System.Xaml support attached name scopes by decorating a class with the [`NameScopePropertyAttribute`](https://msdn.microsoft.com/en-us/library/system.windows.markup.namescopepropertyattribute(v=vs.110).aspx). Perspex needs similar functionality, but it would be nice to not require the use of an attribute.

The question is how to expose this functionality. My first idea is changing the `XamlType.IsNameScope` property to a method such as `INameScope XamlType.GetNameScope(object instance)` which would return `null` if `instance` is not a name scope, or would return the `INameScope` if it is.

One thing to remember is that Perspex doesn't have a dependency on OmniXAML at the core, and as such Perspex's `INameScope` is a different interface. We would most likely deal with this by wrapping the Perspex `INameScope` in an OmniXAML `INameScope` in the `GetNameScope` method.

Other ideas gratefully received however.

**Comment by SuperJMN** [comment]
Your fix is live! :)
