### ISSUE TITLE
Add equivalent of ISupportInitialize

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#58]
Currently, the `Name` property needs to be set before the control is added to the visual tree, as styles can apply to a named control. The way we currently do this is by adding each control to the tree of objects created by OmniXAML *after* its properties have been set.

There are a few problems with this:

1. It means OmniXAML's behavior differs from System.Xaml.
2. It means that when bindings are set up, inherited DataContext values are always initially null, meaning type converters get fired with a null value where they don't in normal XAML, and generally causing irritating problems.

System.Xaml supports [`ISupportInitialize`](http://blogs.msdn.com/b/mikehillberg/archive/2006/09/19/loadedvsinitialized.aspx) which would work around this problem by allowing styling to be applied only *after* all properties have been set (including `Name`!) but still allowing the object to be added to the tree immediately after creation.

We can't use `ISupportInitialize` as it's not available to PCLs so we'd need to find another mechanism. My first idea would be to add `BeginInit` and `EndInit` methods to `XamlType` which could be overridden to call the appropriate Perspex method in `PerspexXamlType`.

**Comment by SuperJMN** [comment]
I'll go for it as soon as I have some time.

**Comment by SuperJMN** [comment]
This was about to be solved. Holding it by now until more urgent issues are fixed.

**Comment by SuperJMN** [comment]
It's done, but it's still not very usable from a API point of view. Stay tuned.

**Comment by SuperJMN** [comment]
Feature added! Just look for the ILoader.Load(Stream, Settings). The Settings class has a ILifecycleListener that you can use to look for events for a given instance.

**Comment by grokys** [comment]
Fantastic! Hopefully I will have chance to try it this week.

**Comment by SuperJMN** [comment]
I have done a quite big refactor in the last few days/weeks. I hope there aren't too many conflicts with Perspex/OmniXAML :)
