### ISSUE TITLE
Attached property on root element is treated as non-attached.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#61]
This relates to https://github.com/Perspex/Perspex/issues/334.

If an attached property is set on the root element, it is treated as a non-attached property. I believe the problem occurs here:

https://github.com/SuperJMN/OmniXAML/blob/master/Source/OmniXaml/ObjectAssembler/ObjectAssembler.cs#L96

...as on that line all information other than the property name is discarded.

**Comment by SuperJMN** [comment]
Fixed! Thanks @grokys !
