### ISSUE TITLE
InvalidCastException in StateCommuter.AssignChildToParentProperty

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#62]
The following Perspex markup throws an exception:

```XAML
    <TreeView Name="foo">
      <TreeViewItem>Hello</TreeViewItem>
    </TreeView>
```

```
Exception thrown: 'System.InvalidCastException' in Perspex.Markup.Xaml.dll

Additional information: Unable to cast object of type 'OmniXaml.Typing.XamlDirective' to type 'OmniXaml.Typing.MutableXamlMember'.
```

**Comment by SuperJMN** [comment]
Whoops, that's strange! Does it work with?

    <ListBox Name="foo">
      <ListBoxItem>Hello</ListBoxItem>
    </ListBox>

**Comment by SuperJMN** [comment]
Yes, with ListBoxItem it works because the inner string "Hello" is set as Content. When the content property is one-to-many, it simply dies. I will have a lot of fun with it :D

Thanks for the report!

**Comment by SuperJMN** [comment]
Fixed with https://github.com/SuperJMN/OmniXAML/commit/cbf49b25119687e7437cd9c47123b5a20c282f84 :D
