### ISSUE TITLE
Name not registered with correct name scope

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#64]
It seems that the Name property is a little special in its handling. Consider the following:

```XAML
<UserControl Name="foo" x:Class="Foo"/>
</UserControl>
```

```XAML
<Window>
    <Foo Name="foo"/>
</Window>
```

Note that `UserControl` and `Window` are both name scopes.

Even though the same property is being set in both examples (`Foo.Name`); in the first example the name should be registered with `Foo`'s own `UserControl` namescope whereas in the second it should be registered with the `Window`'s namescope.

Currently both cause the control to be registered in the `Foo` `UserControl` name scope in OmniXAML.

You may ask why a control would ever want to register itself in it's own name scope. The answer is:

```XAML
<ControlTemplate>
    <ContentControl Name="PART_ContentControl"/>
</ControlTemplate>
```

Here, `ControlControl` will be the name scope for the templated children. Adding itself to its own name scope allows the PART to be found by the parented templated control.

**Comment by SuperJMN** [comment]
Nice finding! I'm sure this issue will be fun to solve :)

**Comment by SuperJMN** [comment]
I think this is solve with the latest change.
