### ISSUE TITLE
Exception: Cannot find a property named "Row" in the type Perspex.Controls.Shapes.Rectangle

### ISSUE THREAD

**Issue by wieslawsoltes** [SuperJMN/OmniXAML#65]
Code to reproduce the issue:

```XAML
<Rectangle Width="100" Height="100" Fill="Red">
    <Grid.Row>1</Grid.Row>
</Rectangle>
```

setting attached properties this way enables to do things like:
```XAML
<Button Name="button" Content="Click Me" HorizontalAlignment="Stretch" Grid.Row="1" VerticalAlignment="Stretch" Margin="0,10,0,10" FontSize="20" Foreground="PaleGrey" Background="DarkGrey">
    <Interactivity:Interaction.Behaviors>
        <Interactions:EventTriggerBehavior EventName="Click" SourceObject="{Binding ElementName=button}">
            <Interactions:ChangePropertyAction TargetObject="{Binding ElementName=DataTriggerText}" PropertyName="Text" Value="PaleYellow"/>
        </Interactions:EventTriggerBehavior>
    </Interactivity:Interaction.Behaviors>
</Button>
```

where `Interactivity:Interaction.Behaviors` is an attached property.

**Comment by SuperJMN** [comment]
Very very interesting issue! I'm really looking forward to this one 😀

**Comment by wieslawsoltes** [comment]
Yes, this enables a lot of possibilities.

This https://github.com/wieslawsoltes/Perspex/tree/Interactivity is my port of https://github.com/Microsoft/XamlBehaviors to Perspex.

I have some sample Xaml for this issue here: https://github.com/wieslawsoltes/Perspex/blob/Interactivity/samples/XamlTestApplicationPcl/Views/MainWindow.paml#L278

**Comment by wieslawsoltes** [comment]
This Xaml:
```XAML
<Rectangle Width="100" Height="100" Fill="Red">
    <Grid.Row>1</Grid.Row>
</Rectangle>
```
is equal to this Xaml:
```XAML
<Rectangle Width="100" Height="100" Fill="Red" Grid.Row="1"/>
```
so I think there is already an existing functionality in `OmniXaml` for recognizing and handling the attached properties when set at attribute level.

**Comment by SuperJMN** [comment]
Thanks a lot, Wiesław, for the extra information! I'm going with this issues very soon :D

**Comment by SuperJMN** [comment]
Fixed! Please, check it!
