### ISSUE TITLE
How to create an object from XAML?

### ISSUE THREAD

**Issue by KeKl** [SuperJMN/OmniXAML#68]
Hi,

Say I have following XAML:

    <m:ModuleCatalog xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:m="clr-namespace:Microsoft.Practices.Prism.Modularity;assembly=Microsoft.Practices.Prism.Composition"
                    >
    <m:ModuleInfo ModuleName="MyModule" ModuleType="ModulHandling.Module.MyModule, ModulHandling.Module, Version=1.0.0.0" Ref="file://ModulHandling.Module" />
    </m:ModuleCatalog>

How can I construct a object with OmniXAML?

**Comment by SuperJMN** [comment]
Please, take a look at the sample application I've created in \Test Applications\BasicSample :)

I hope you'll get the picture.
This is all you need:

https://github.com/SuperJMN/OmniXAML/blob/master/Source/Tests/TestApplications/BasicModel/Program.cs#L16

Along with this:
https://github.com/SuperJMN/OmniXAML/blob/master/Source/Tests/TestApplications/BasicModel/Properties/AssemblyInfo.cs#L39

And the attributes in the sample model classes.

Thanks for your question!
