### ISSUE TITLE
Pass (optional) URL when loading XAML

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#70]
We need to be able to pass a URL to OmniXAML which needs to be passed to `TypeConverter`s somehow:

- When loading resources, we need to know which assembly and resource path the current XAML file is being loaded from.
- When reporting an error, if there are `UserControl`s in the XAML it's not clear which file caused the exception.

**Comment by SuperJMN** [comment]
You can now provide a dictionary of arbitrary objects in the Settings class (it will be passed in the IValueContext for Markup Extensions and TypeConverters).
