### ISSUE TITLE
Allow any class to be a markup extension.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#74]
System.Xaml allows any class to be a markup extension, but as far as I can tell to be a markup extension in OmniXAML, for a markup extension called e.g. "Foo" the class needs to be called `FooExtension`.

In WPF, the `Binding` class is itself a markup extension:

http://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Data/BindingBase.cs,63

This would eliminate having to create e.g. a `BindingExtension` class which then copies its properties to a `Binding` object in `ProvideValue`.

This isn't high priority, just a difference I noticed.

**Comment by SuperJMN** [comment]
Yes, I know! But how could I map markup to a runtime type? I currently do it adding "Extension" to the text. I have looked for how System.Xaml does it, but I found nothing. Also, I think Binding is the only that doesn't end in "Extension".

**Comment by jogibear9988** [comment]
You could at first search for a Type "BlaBlaExtension", if no one found search for "BlaBla". I think WPF does it the same way. (C# does it the same with Attributes). And in WPF every MarkupExtension derrives from MarkupExtension.

**Comment by SuperJMN** [comment]
Nice approach. I will implement that in OmniXAML V2
