### ISSUE TITLE
Attached properties not recognised

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#76]
The following XAML:

```
  <TextBlock Text="Hello">
    <ToolTip.Tip>
      <TextBlock>Tip</TextBlock>
    </ToolTip.Tip>
  </TextBlock>
```

Gives the error:

> Cannot find a property named "Tip" in the type Perspex.Controls.TextBlock

This isn't right - its an attached property.

**Comment by wieslawsoltes** [comment]
I think this was fixed by https://github.com/SuperJMN/OmniXAML/issues/65

**Comment by SuperJMN** [comment]
Yes, this is fixed :) Hopefully! I was a hard one.
