### ISSUE TITLE
Two DropDowns have SelectedIndex set, only the first works

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#77]
You can see the code here:

https://github.com/Perspex/Perspex/blob/master/samples/ControlCatalog/Pages/DropDownPage.paml#L7

Two `DropDown`s are created in the XAML, both with a `SelectedIndex` property. However it only ever gets set on the first one - you can swap them around in the XAML and the same happens.

Appears to be a problem in OmniXAML. I think it may be related to the fact the `SelectedIndex` is a `DependsOn` property.

**Comment by SuperJMN** [comment]
I have reproduced it. Definitely, there is a problem here!

**Comment by SuperJMN** [comment]
Fixed :dart:
