### ISSUE TITLE
Lazy load metadata

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#79]
I'm not sure if this problem is a Perspex problem or if it's a OmniXAML problem. The problem manifests itself in two ways:

# Assembly not loaded

The problem is that a XAML file may contain a type in an assembly that is not loaded at the time of creation of `PerspexRuntimeTypeSource`. For example in @wieslawsoltes [XamlBehaviors](https://github.com/XamlBehaviors/XamlBehaviors) project there is this line:

https://github.com/XamlBehaviors/XamlBehaviors/blob/master/samples/XamlTestApplicationPcl/Views/MainWindow.paml#L16

At the time of initializing the `PerspexRuntimeTypeSource` the `Perspex.Xaml.Interactions` assembly that contains the `<ia:EventTriggerBehavior>` class isn't loaded, so its attributes haven't been scanned to find the `[Content]` attribute, meaning that OmniXAML can't find its content property.

# Slow loading times

If you run the XamlTestApplication in XamlBehaviors, startup is *really* slow - it takes about 7 seconds to get to the point of failure on my machine! This is caused because the `PerspexRuntimeTypeSource` is created for each XAML load, and there is a XAML file for each control's template, and all of the assemblies are rescanned each time.

# Solution

My suggested solution would be to load metadata (content property, type converters, xml namespace mappings etc) lazily. This way we can construct a `PerspexRuntimeTypeSource` once and reuse it for all loads.

**Comment by grokys** [comment]
Actually, I've noticed that application startup time has significantly increased after the move to the latest OmniXAML - it wasn't noticeable before.

**Comment by grokys** [comment]
Looking at it some more, I think the slowdown is caused in part by lots of exceptions getting thrown by `EnumExtensions.TryParse` and in part by the fact we're now scanning all assemblies for `[Content]` attributes instead of a select few Perspex assemblies.

**Comment by SuperJMN** [comment]
The top priority is to eliminate the need of the try-catch block in Glass\EnumExtensions\TryParse. The shared context is totally needed. We only need one context!

**Comment by SuperJMN** [comment]
I'll close this until it's really necessary.
