### ISSUE TITLE
Need access to TopDownValueContext in MemberValuePlugin

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#80]
The following fails:

https://github.com/XamlBehaviors/XamlBehaviors/blob/master/samples/XamlTestApplicationPcl/Views/MainWindow.paml#L16

The reason for this is that `ia:EventTriggerBehavior` is not a control, and it's trying to bind `ElementName=button` to one of its properties but Perspex doesn't know where to *look* for a control named `button`: you need an 'anchor' control to locate a name scope to search for a named control!

The solution is to use `TopDownValueContext` to search up the tree for the nearest control, however it's not available in `MemberValuePlugin` as far as I can see.

**Comment by SuperJMN** [comment]
Haha, great! I understand the need to do that. I will add a link to the TopDownValueContext for cases like this! I hope it doesn't clutter the rest of the design :)

**Comment by grokys** [comment]
I updated to the latest OmniXAML and overrode `Member.SetValue` but I still didn't have access to the `TopDownMemberContext` in `Member`.

To work around it, I hacked OmniXAml to pass a `ValuePipeline` to `Member.SetValue` (`ValuePipeline` is actually needed in `Member.SetValue` too [1]) and exposed the `TopDownValueContext` that's stored in there.

However, I get stuck here. I need to get the most recent element that either implements `IControl` or derives from `Control` but there doesn't seem to be any way to do that in `TopDownValueContext`: you can only get an element by exact type.

I think in System.Xaml this method could be used to find what I want: https://msdn.microsoft.com/en-us/library/ff406871(v=vs.110).aspx

[1] : [here we have to create a new `ValuePipeline`: ](https://github.com/Perspex/Perspex/blob/master/src/Markup/Perspex.Markup.Xaml/Context/PerspexXamlMemberValuePlugin.cs#L56)

**Comment by grokys** [comment]
Also this issue is really causing me problems now!

**Comment by SuperJMN** [comment]
Take a look at this! https://github.com/SuperJMN/OmniXAML/commit/e21ae28fde9104333aa9a260ebc35053611c4772
