### ISSUE TITLE
INamespaceRegistry API

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#81]
I don't understand the INamespaceRegistry API. There are many methods that are very similar and I don't understand the differences between them:

- GetNamespaceByPrefix
- GetXamlNamespaceNameByPrefix
- GetXamlNamespace
- GetNamespace
- GetXamlNamespaceByPrefix

**Comment by SuperJMN** [comment]
That is a complete mess. You're right!

**Comment by grokys** [comment]
I was looking at the `NamespaceRegistry` class not the interface - the interface is much cleaner.
