### ISSUE TITLE
Doesn't correctly handle xmlns on child elements

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#82]
Consider the following XAML:

```
    <ListBox>
        <ListBoxItem xmlns:sys="clr-namespace:System;assembly=mscorlib">
            <!-- Here sys: exists -->
            <sys:String>Hello</sys:String>
        </ListBoxItem>
        <ListBoxItem>
            <!-- Here sys: doesn't exist -->
            <sys:String>Hello</sys:String>
        </ListBoxItem>
    </ListBox>
```

I don't believe OmniXAML will handle this correctly currently - the `sys:` xmlns will leak to the second `ListBoxItem`.

**Comment by SuperJMN** [comment]
No, it doesn't handle them. I have to think how to implement it thoroughly. Thanks for reporting it! I knew this would came to bit me one day or another 😄

**Comment by wieslawsoltes** [comment]
@SuperJMN I run into this problem recently when using `Static` in `Avalonia`.

This line https://github.com/Core2D/Core2D/blob/0205014255ba1aaffa57c6f74152b8f1f8672e2b/src/Core2D.Avalonia/Windows/MainWindow.xaml#L25 
compiles and runs without problems even if I remove this prefix definition 
https://github.com/Core2D/Core2D/blob/0205014255ba1aaffa57c6f74152b8f1f8672e2b/src/Core2D.Avalonia/Windows/MainWindow.xaml#L9.

Only when using `Android` platforms it throws an exception.

**Comment by SuperJMN** [comment]
Fixed in v2!
