### ISSUE TITLE
Cannot add Color to WPF resource dictionary.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#85]
Testing using the following (WPF) XAML:

```
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
  <Window.Resources>
    <Color x:Key="color">#ff808080</Color>
  </Window.Resources>
</Window>
```

Gives the error: `Error loading XAML: System.ArgumentNullException: Key cannot be null.`

**Comment by grokys** [comment]
Sent a PR for what I hope is the correct fix.

**Comment by SuperJMN** [comment]
Quick question! Is the color code (#ff808080) inside the tags the Content Property of SolidColorBrush?

**Comment by grokys** [comment]
This was fixed by the PR you merged!

But no, the color code isn't the `[ContentProperty]` - XAML supports direct creation of objects via the `TypeConverter` in situations like this, and OmniXAML supports that.
