### ISSUE TITLE
Cannot add SolidColorBrush to WPF resource dictionary.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#87]
Following on from #85 - when the PR that fixes that issue is applied (#86) the following XAML fails with a NullReferenceException:

```
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
  <Window.Resources>
    <SolidColorBrush x:Key="brush">#ff808080</SolidColorBrush>
  </Window.Resources>
</Window>
```

**Comment by grokys** [comment]
I've added a fix for this issue, but it causes XAML that should fail to be parsed. For example, the following XAML:

```
<Window.Resources>
    <ColumnDefinition x:Key="col">Foo</ColumnDefinition>
</Window.Resources>
```

Causes the string "Foo" to be written to `Window.Resources` when instead the parse should fail. This is because if type conversion fails on a value, the unconverted value is passed through instead. If OmniXAML is changed to throw an exception when the value cannot be converted, then Bindings start to fail as the `Binding` object can't be converted to the target type.

**Comment by grokys** [comment]
Looking at the WPF source, it seems the way that `Binding` is handled is based on the way the `XamlXmlReader` and the `XamlObjectWriter` classes interact. When the WPF loader takes a node from the `XamlXmlReader` it checks to see if a `BindingBase` is being applied to a `XamlMember`, and if so uses its own code to set the binding on the property.

This has the advantage that values that cannot be converted usually cause an exception. However, I'm not sure there's a way to place code between OmniXaml's equivalent of `XamlXmlReader` and `XamlObjectWriter`?

**Comment by grokys** [comment]
This has moved down in priority now because I have the hack in #88 which is working well enough for now...

**Comment by SuperJMN** [comment]
<Window.Resources>
        <Style x:Key="Style">
            <Setter Value="12" Property="Margin"  />
        </Style>
        <SolidColorBrush x:Key="RedBrush">Red</SolidColorBrush>
        <SolidColorBrush x:Key="GrayBrush">#ff808080</SolidColorBrush>
    </Window.Resources>

![image](https://cloud.githubusercontent.com/assets/3109851/13202664/7c2b1f2c-d8a2-11e5-8a8a-e6125723d38a.png)
