### ISSUE TITLE
CI is broken.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#95]
AppVeyor CI is currently broken.

**Comment by grokys** [comment]
I tried to fix this but the naming of tests (#96) is hurting my head so I give up...

**Comment by SuperJMN** [comment]
I have fixed the names! How do you make CI work again? Thanks!

**Comment by wieslawsoltes** [comment]
I have fixed CI, see my pull request #98. Also I have migrated all `OmniXAXML` tests to `Xunit`.
