### ISSUE TITLE
Test directory naming is confusing.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#96]
The test projects and their parent directory names differ in confusing ways:

- `OmniXaml.Services.DotNetFx.Tests.csproj` is in `OmniXaml.AppServices.NetCore.Tests`
- `OmniXaml.Services.Tests.csproj` is in `OmniXaml.AppServices.Tests` *and* its assembly name is `OmniXaml.AppServices.Tests.dll`
- `OmniXaml.Tests.Common.DotNetFx.csproj` is in `OmniXaml.Test.Common.NetCore`

**Comment by SuperJMN** [comment]
Fixed!
